spring:
  application:
    name: quiz-backend
  
  datasource:
    url: jdbc:h2:mem:quizdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: false  # Disabled for security
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  cache:
    type: simple

# OpenAI Configuration
openai:
  api-key: ${OPENAI_API_KEY:}
  model: gpt-4o-mini
  base-url: https://api.openai.com/v1

# RAG (Retrieval-Augmented Generation) Configuration
rag:
  enabled: true
  wikipedia:
    enabled: true
    max-articles: 3
    max-content-length: 2000
  retrieval:
    timeout-seconds: 10
    fallback-on-error: true

# Google Search Configuration (Optional - for better results)
google:
  search:
    api-key: ${GOOGLE_SEARCH_API_KEY:}
    cx: ${GOOGLE_SEARCH_CX:}

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.entrata.quiz: DEBUG
    org.springframework.web: DEBUG
